# Generated by Django 2.0.6 on 2018-07-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='name')),
                ('finished', models.BooleanField(db_index=True, default=False, verbose_name='finished')),
                ('dropped', models.BooleanField(db_index=True, default=False, verbose_name='dropped')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='habit creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='formed/dropped date and ime')),
            ],
            options={
                'verbose_name_plural': 'habits',
                'verbose_name': 'habit',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='creation date and time')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.Habit', verbose_name='habit')),
            ],
            options={
                'verbose_name_plural': 'habit logs',
                'verbose_name': 'habit log',
                'ordering': ['-created'],
            },
        ),
    ]
